# Generated by Django 3.2.4 on 2021-08-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Passward',
            new_name='password',
        ),
    ]
